### ISSUE TITLE
Cannot download Dependency-Check executable

### ISSUE THREAD

**Issue by rtau-cca** [entur/owasp-orb#17]
When tried to use `owasp/commandline_owasp_dependency_check`, the following error was found and stopped the pipeline.
```
Downloading Dependency-Check executable version 6.1.2 from https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.1.2-release.zip ..

Exited with code exit status 8
CircleCI received exit code 8
```

When tried to retrieve that URL, 404 is returned. It seems the binary is hosted on GitHub instead of Bintray, as in https://jeremylong.github.io/DependencyCheck/dependency-check-cli/index.html

In addition, I have tried to override executable_url with, then the orbs command can be executed successfully:
```
echo 'export executable_url=https://github.com/jeremylong/DependencyCheck/releases/download/vVERSION/dependency-check-VERSION-release.zip' >> $BASH_ENV

**Comment by Pavloro** [comment]
Hi! It should be fixed in version 0.0.15
